// Demo data for Events category components
// This file contains sample data used for component previews and documentation

import type { Event, EventDetails } from "../types";

// Helper to generate dates relative to today
const getDateAt = (daysFromNow: number, hour: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

// Single event for EventCard default
export const demoEvent: Event = {
  ageRestriction: "21+",
  aiSummary:
    "Immersive electronic night with world-class DJs and stunning visuals at LA's top-rated venue.",
  category: "Music",
  city: "Los Angeles",
  dateTime: "Tonight 9:00 PM - 3:00 AM",
  eventSignal: "going-fast",
  hasMultipleDates: true,
  image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800",
  lineup: ["DJ Shadow", "Bonobo", "Four Tet", "Caribou"],
  neighborhood: "Echo Park",
  organizerRating: 4.8,
  priceRange: "$45 - $150",
  reviewCount: 12_453,
  ticketTiers: [
    "General Admission $45",
    "VIP Access $120",
    "Backstage Pass $150",
  ],
  title: "NEON Vol. 9",
  venue: "Echoplex",
  venueRating: 4.8,
  vibeDescription:
    "Immersive electronic experience with world-class DJs and stunning visuals.",
  vibeTags: ["High energy", "Late night", "Dressy"],
};

// 15 events for EventList default
export const demoEvents: Event[] = [
  {
    ageRestriction: "21+",
    category: "Music",
    city: "Los Angeles",
    coordinates: { lat: 34.0781, lng: -118.2606 },
    dateTime: "Tonight 9:00 PM - 3:00 AM",
    eventSignal: "going-fast",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800",
    neighborhood: "Echo Park",
    organizerRating: 4.8,
    priceRange: "$45 - $150",
    reviewCount: 12_453,
    title: "NEON Vol. 9",
    venue: "Echoplex",
    vibeTags: ["High energy", "Late night"],
  },
  {
    category: "Comedy",
    city: "Los Angeles",
    coordinates: { lat: 34.0195, lng: -118.4912 },
    dateTime: "Tonight 10:00 PM - 12:00 AM",
    discount: "TONIGHT ONLY - 40% OFF",
    eventSignal: "popular",
    image: "https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800",
    neighborhood: "Santa Monica",
    organizerRating: 4.7,
    priceRange: "$15 - $35",
    reviewCount: 3241,
    title: "The Midnight Show",
    venue: "The Comedy Underground",
    vibeTags: ["Social", "Late night"],
  },
  {
    category: "Classes",
    city: "Los Angeles",
    coordinates: { lat: 34.0731, lng: -118.2608 },
    dateTime: "Saturday 6:00 PM - 10:00 PM",
    eventSignal: "just-added",
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=800",
    neighborhood: "Echo Park",
    organizerRating: 4.9,
    priceRange: "Free",
    reviewCount: 8764,
    title: "Salsa Sundays @ Echo Park",
    venue: "Echo Park Lake",
    vibeTags: ["High energy", "Social"],
  },
  {
    category: "Classes",
    city: "Los Angeles",
    coordinates: { lat: 34.1365, lng: -118.2943 },
    dateTime: "Tomorrow 6:00 AM - 8:00 AM",
    discount: "FREE - First 50 Only",
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800",
    neighborhood: "Los Feliz",
    organizerRating: 4.9,
    priceRange: "Free",
    reviewCount: 8764,
    title: "Dawn Flow: Griffith Park",
    venue: "Griffith Park",
    vibeTags: ["Chill", "Wellness", "Outdoor"],
  },
  {
    category: "Sports",
    city: "Los Angeles",
    coordinates: { lat: 34.043, lng: -118.2673 },
    dateTime: "Friday 7:30 PM - 10:30 PM",
    eventSignal: "sales-end-soon",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800",
    neighborhood: "Downtown",
    organizerRating: 4.5,
    priceRange: "$125 - $850",
    reviewCount: 2341,
    title: "Lakers vs Celtics",
    venue: "Crypto.com Arena",
    vibeTags: ["High energy", "Social", "Premium"],
  },
  {
    category: "Food & Drink",
    city: "Los Angeles",
    coordinates: { lat: 34.0341, lng: -118.2324 },
    dateTime: "Sunday 10:00 AM - 4:00 PM",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    neighborhood: "Arts District",
    organizerRating: 4.8,
    priceRange: "Free",
    reviewCount: 5632,
    title: "Smorgasburg LA: Sunday Market",
    venue: "ROW DTLA",
    vibeTags: ["Family-friendly", "Outdoor", "Social"],
  },
  {
    ageRestriction: "21+",
    category: "Arts",
    city: "Los Angeles",
    coordinates: { lat: 34.0639, lng: -118.3592 },
    dateTime: "Friday 7:00 PM - 11:00 PM",
    discount: "MEMBER PRICE",
    image: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=800",
    neighborhood: "Miracle Mile",
    organizerRating: 4.7,
    priceRange: "$35 - $75",
    reviewCount: 1234,
    title: "LACMA After Hours",
    venue: "LACMA",
    vibeTags: ["Chill", "Date night", "Sophisticated"],
  },
  {
    category: "Music",
    city: "Los Angeles",
    coordinates: { lat: 34.1122, lng: -118.3391 },
    dateTime: "Saturday 8:00 PM - 11:00 PM",
    image: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800",
    lineup: ["Kamasi Washington", "Thundercat", "Terrace Martin"],
    neighborhood: "Hollywood Hills",
    organizerRating: 4.8,
    priceRange: "$45 - $200",
    reviewCount: 12_453,
    title: "Blue Note Under Stars",
    venue: "Hollywood Bowl",
    vibeTags: ["Chill", "Date night", "Outdoor"],
  },
  {
    ageRestriction: "21+",
    category: "Nightlife",
    city: "Los Angeles",
    coordinates: { lat: 34.0928, lng: -118.3287 },
    dateTime: "Saturday 10:00 PM - 4:00 AM",
    image: "https://images.unsplash.com/photo-1571266028243-e4733b0f0bb0?w=800",
    lineup: ["Amelie Lens", "I Hate Models", "FJAAK"],
    neighborhood: "Hollywood",
    organizerRating: 4.6,
    priceRange: "$35 - $65",
    reviewCount: 1876,
    title: "Meraki: Seth Troxler",
    venue: "Sound Nightclub",
    vibeTags: ["High energy", "Late night", "Underground"],
  },
  {
    ageRestriction: "18+",
    category: "Comedy",
    city: "Los Angeles",
    coordinates: { lat: 34.0901, lng: -118.3615 },
    dateTime: "In 2 days 8:00 PM - 11:00 PM",
    image: "https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800",
    neighborhood: "Hollywood",
    organizerRating: 4.7,
    priceRange: "$25 - $55",
    reviewCount: 3241,
    title: "Whitney Cummings + Friends",
    venue: "The Laugh Factory",
    vibeTags: ["Chill", "Social", "Date night"],
  },
  {
    category: "Music",
    city: "Los Angeles",
    coordinates: { lat: 33.985, lng: -118.4695 },
    dateTime: "Sunday 4:00 PM - 8:00 PM",
    eventSignal: "popular",
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800",
    neighborhood: "Venice",
    organizerRating: 4.6,
    priceRange: "Free",
    reviewCount: 2145,
    title: "Venice Beach Drum Circle",
    venue: "Venice Beach Boardwalk",
    vibeTags: ["Outdoor", "Social", "Chill"],
  },
  {
    category: "Film",
    city: "Los Angeles",
    coordinates: { lat: 34.0407, lng: -118.2468 },
    dateTime: "Friday 8:30 PM - 11:00 PM",
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800",
    neighborhood: "DTLA",
    organizerRating: 4.8,
    priceRange: "$25 - $45",
    reviewCount: 892,
    title: "Rooftop Cinema: Blade Runner",
    venue: "Rooftop Cinema Club",
    vibeTags: ["Date night", "Views", "Chill"],
  },
  {
    category: "Sports",
    city: "Los Angeles",
    coordinates: { lat: 34.0739, lng: -118.24 },
    dateTime: "Saturday 1:10 PM - 4:30 PM",
    eventSignal: "few-tickets-left",
    image: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800",
    neighborhood: "Elysian Park",
    organizerRating: 4.7,
    priceRange: "$35 - $350",
    reviewCount: 15_678,
    title: "Dodgers vs Giants",
    venue: "Dodger Stadium",
    vibeTags: ["Family-friendly", "Social", "High energy"],
  },
  {
    ageRestriction: "21+",
    category: "Food & Drink",
    city: "Los Angeles",
    coordinates: { lat: 34.0508, lng: -118.249 },
    dateTime: "Sunday 12:00 PM - 6:00 PM",
    eventSignal: "just-added",
    image: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800",
    neighborhood: "Downtown",
    organizerRating: 4.5,
    priceRange: "$45 - $85",
    reviewCount: 567,
    title: "Natural Wine Fair",
    venue: "Grand Central Market",
    vibeTags: ["Tasting", "Social", "Sophisticated"],
  },
  {
    category: "Wellness",
    city: "Los Angeles",
    coordinates: { lat: 34.078, lng: -118.4741 },
    dateTime: "Sunday 7:00 AM - 9:00 AM",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800",
    neighborhood: "Brentwood",
    organizerRating: 4.9,
    priceRange: "Free",
    reviewCount: 1234,
    title: "Meditation in the Gardens",
    venue: "The Getty Center",
    vibeTags: ["Wellness", "Outdoor", "Chill"],
  },
];

// Detailed event for EventDetail default
export const demoEventDetails: EventDetails = {
  aiSummary: "Raw, unfiltered techno in an authentic warehouse setting.",
  attendeesCount: 537,
  category: "Nightlife",
  city: "Houston, TX",
  description:
    "Experience the raw energy of underground techno. Industrial beats, immersive visuals, and a crowd that lives for the music.",
  endDateTime: getDateAt(3, 4),
  eventSignal: "going-fast",
  faq: [
    {
      answer: "No refunds. Tickets are transferable.",
      question: "What is the refund policy?",
    },
    {
      answer: "Open 2 hours before event.",
      question: "When do doors open?",
    },
    {
      answer: "Limited, leave early to avoid long queues.",
      question: "Is there parking?",
    },
  ],
  friendsGoing: [
    { avatar: "https://i.pravatar.cc/40?u=alex", name: "Alex" },
    { avatar: "https://i.pravatar.cc/40?u=sam", name: "Sam" },
  ],
  goodToKnow: {
    ageRestriction: "21+",
    doorsOpen: "7:00 PM",
    dressCode: "Casual",
    duration: "2 hours",
    parking: "Limited, leave early to avoid long queues",
    showtime: "7:30 PM",
  },
  images: [
    "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800",
    "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800",
    "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800",
  ],
  lineup: ["Amelie Lens", "I Hate Models", "FJAAK"],
  neighborhood: "The Woodlands",
  organizer: {
    eventsCount: 154,
    followers: 1200,
    hostingYears: 8,
    image: "https://i.pravatar.cc/80?u=midnight",
    name: "Midnight Lovers",
    rating: 4.5,
    responseRate: "very responsive",
    reviewCount: 1067,
    trackRecord: "great",
    verified: true,
  },
  policies: {
    entry: "Open 2 hours before event",
    idRequired: true,
    refund: "No refunds. Tickets are transferable.",
    securityOnSite: true,
  },
  priceRange: "$15 - $30",
  relatedTags: ["Houston Events", "Texas Nightlife", "Techno Parties"],
  startDateTime: getDateAt(2, 22),
  tiers: [
    { available: 50, name: "General Admission", price: 15 },
    {
      available: 20,
      benefits: ["Skip the line", "Exclusive lounge"],
      name: "VIP Access",
      price: 30,
    },
  ],
  title: "Sunglasses at Night: Underground Techno",
  venue: "The White Rabbit",
  venue_details: {
    address: "8827 Nasher Ave",
    city: "Houston TX",
    coordinates: { lat: 29.7604, lng: -95.3698 },
    name: "The White Rabbit",
  },
  vibeTags: ["High energy", "Late night", "Underground"],
};

// Ticket tiers for TicketTierSelect
export const demoTicketTiers = [
  {
    available: 100,
    fee: 5,
    id: "1",
    maxPerOrder: 10,
    name: "General Admission",
    price: 45,
  },
  {
    available: 20,
    description: "Includes backstage access",
    fee: 15,
    id: "2",
    maxPerOrder: 4,
    name: "VIP",
    price: 150,
  },
];

// Event confirmation data
export const demoEventConfirmation = {
  eventDate: "Jan 20, 2024",
  eventLocation: "Central Park, New York",
  eventTitle: "Summer Music Festival",
  orderNumber: "EVT-12345",
  organizer: {
    name: "Live Nation",
  },
  recipientEmail: "customer@example.com",
  ticketCount: 2,
};
